"""empty message

Revision ID: 6bedc76eecbc
Revises: a95dc8c574e0
Create Date: 2025-02-24 12:01:03.069991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bedc76eecbc'
down_revision = 'a95dc8c574e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_damaged', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('quantity_damaged')

    # ### end Alembic commands ###
